---

docker_daemon_config:
  'log-driver': journald
  # Контейнерам ближе и быстрее ходить в DNS Яндекса,
  # т.к. мы разворачиваем виртуальную машину в облаке Яндекса. 
  'dns':
    - 77.88.8.8
    - 77.88.8.1
