- name: create directory for analyzer app
  file:
    path: /etc/docker/compose/analyzer
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: deploy docker-compose.yml for analyzer app
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/analyzer/docker-compose.yml
    mode: 0640
    owner: root
    group: docker
  notify:
    - restart analyzer

- name: start & enable analyzer service
  service:
    name: docker-compose@analyzer
    # Сервис должен запускаться после перезагрузки
    enabled: yes
    # Сервис должен запуститься или быть уже запущен
    state: started

# Требуется для модуля docker_container
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements
- name: install python modules
  apt:
    name:
      - python3-docker
    update_cache: yes

# Требуется чтобы все обработчики (handlers) отработали немедленно,
# не дожидаясь обычных точек синхронизации
# https://docs.ansible.com/ansible/latest/modules/meta_module.html#parameters
- name: flush handlers
  meta: flush_handlers

- name: apply database migrations
  docker_container:
    name: db_migrator
    image: "{{ analyzer_image }}"
    command: ["analyzer-db", "upgrade", "head"]
    networks:
      - name: analyzer_default
    auto_remove: yes
    networks_cli_compatible: yes
    env:
      ANALYZER_PG_URL: postgresql://{{ analyzer_pg_user }}:{{ analyzer_pg_password }}@postgres/{{ analyzer_pg_dbname }}
